server:
  port: 8081
  tomcat:
    threads.max: 50
    max-connections: 100
    max-http-form-post-size: 35MB
    connection-timeout: 60000

mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0

spring:
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB

  mail:
    host: smtp.qq.com
    username: 124331641@qq.com
    password: zqitaxlklewhbiia
    default-encoding: utf-8
    protocol: smtp
    port: 465
    properties:
      mail:
        smtp:
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
          ssl:
            enable: true

  datasource:
    username: root
    password: Pyz@123456
    url: jdbc:mysql://39.101.71.33:3306/poetize?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver

user:
  code:
    format: 【puyunzhu.cn】%s为本次验证的验证码，请在5分钟内完成验证。为保证账号安全，请勿泄漏此验证码。
  subscribe:
    format: 【puyunzhu.cn】您订阅的专栏【%s】新增一篇文章：%s。

store:
  type: qiniu

local:
  enable: true
  uploadUrl: /www/wwwroot/
  downloadUrl: s5cjqld3d.hd-bkt.clouddn.com/


qiniu:
  enable: true
  accessKey: InMgJgkScAKS3tEaLLzjAQ5QIj7DvDhrB9gnY17p
  secretKey: 4G18ujlX_T0kuWV4tI54ai-296o2Z_ZrK2swzVD-
  bucket: pyz-storage
  downloadUrl: www.puyunzhu.cn/


